version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "========= Logging in to Amazon ECR... =========="
#      - apt update
      - apt -y install awscli
      - $(aws ecr get-login --no-include-email --region eu-central-1)      
  build:
    commands:
      - echo Hello PANDA 
      - echo build_commands started on `date`
  post_build:
    commands:
      - ls -la
      - pwd
      - echo post_build_commands completed on `date` 
