version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "========= pre_build commands... =========="
      - docker run hello-world && echo "docker is OK"
      - aws s3 ls && echo "awscli is OK"
#      - apt update
#      - apt -y install awscli
#      - $(aws ecr get-login --no-include-email --region eu-central-1)      
  build:
    commands:
      - echo "========= build commands... =========="
      - echo build_commands started on `date`
  post_build:
    commands:
      - echo "========= post_build commands... =========="
      - ls -la
      - pwd
      - echo post_build_commands completed on `date` 
