version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Hello PANDA
      - echo build_commands started on `date`
  post_build:
    commands:
      - ls -la
      - pwd
      - echo post_build_commands completed on `date` 
